# This is a config for E2B sandbox template.
# You can use template ID (0khmp6kkdm6k5dt26b2z) or template name (lazydev-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lazydev-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("lazydev-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lazydev-test-2')

team_id = "cb1cbc71-848d-4f25-a3d1-27fe585ec081"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lazydev-test-2"
template_id = "0khmp6kkdm6k5dt26b2z"
